### ISSUE TITLE
GroupBy article: "Chaining pure functions" example produces different output

### ISSUE THREAD

**Issue by dylan-kerr** [charpeni/charpeni.com#37]
This relates to `posts/array-prototype-group-by-to-the-rescue.mdx`. Nice succinct article! This issue doesn't really detract from the value of the article, but I thought I'd mention it in case it confuses anyone else.

The "Chaining pure functions" example produces an array of objects, with each object containing a single key (the type). It's also somewhat indirect in converting back and forth from arrays to objects unnecessarily.

In short, I think you could replace:

```javascript
Object.values({
  ...Array.from(new Set(items.map(({ type }) => type))),
}).map((type) => ({ [type]: items.filter((item) => item.type === type) }));
```

with:

```javascript
Object.fromEntries(
  Array.from(new Set(items.map(({ type }) => type)))
    .map((type) => [type, items.filter((item) => item.type === type)])
)
```

to produce the same output as the `.groupBy` proposal and other examples.

**Comment by charpeni** [comment]
Oops, that's right it produces an array of objects which is incorrect. Thanks for flagging this!

I hope no one will be using this though, but I appreciated your intervention to make sure the output is always the same by leveraging [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) to simplify things.

I'll create a PR and I'll add you as the author. Thank you @dylan-kerr!
